image: mcr.microsoft.com/dotnet/core/sdk:latest

stages: 
  - build
  - test

variables:
    test: "Shapes.Test"

before_script:
    - "cd src"
    - "dotnet restore"

build applications:
    stage: build
    script: 
        - "dotnet build"
    artifacts:
        paths:
            - ./**/bin

run unit test app:
  stage: test
  script:
    - "cd $test"
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml



