  trigger:
  - main

variables:
  buildConfiguration: 'Release'
  imageName: 'shapes-api'

stages:
  - stage: 'Build'
    displayName: 'build and test'
    jobs: 
    - job: 'Build and Test'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
        command: 'test'
        projects: 'Shapes.Api/Shapes.Test.csproj'

  - stage: 'Docker'
    displayName: 'docker build'
    jobs:
    - job: 'Pack and Push'
        pool:
          vmImage: 'ubuntu-latest'
      steps:
    - task: Docker@1
      displayName: 'build the docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: 'ShapesApi/Dockerfile'
        arguments: '--build-arg PAT=$(NugetToken)'
        imageName: '$(imageName)'
        useDefaultContext: false
        buildContext: 'ShapesApi'
