trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'release'

stages:
  - stage: 'build'
    displayName: 'build_and_test'
    jobs: 
    - job: 'build'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build'
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '**/*.csproj'

    - job: 'test'
      dependsOn: 'build'
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: 'test'
          projects: 'Shapes.Test/Shapes.Test.csproj'

  - stage: 'docker'
    displayName: 'docker'
    jobs:
    - job: 'build docker image'
      steps:
      - task: Docker@1     
        displayName: 'Build the Docker image'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'Docker Hub'
          command: 'Build an image'
          dockerFile: 'Shapes-api/Dockerfile'
          arguments: '--build-arg BuildId=$(Build.BuildId) --build-arg PAT=$(NugetToken)'
          imageName: 'shapes-api'
          useDefaultContext: false
          buildContext: 'ShapesApi'
